### ISSUE TITLE
Can dmrseq be used to call DMR in the context of CHG and CHH

### ISSUE THREAD

**Issue by Linhua-Sun** [kdkorthauer/dmrseq#1]
Hi, I have a little question. I am wondering if dmrseq can call DMR from CHG and CHH. These methylation contexts are usual in the brain and plants' genome. Their distribution and contents are different from CG.
Thank you!

**Comment by kdkorthauer** [comment]
Hi Linhua-Sun,

Thanks for reaching out. Yes, dmrseq can be applied to other organisms and methylation contexts, provided you can obtain counts of methylated reads and total coverage counts for each position of interest. The approach is not specific to CpG loci, although this was what we analyzed in the manuscript based on the datasets we were using.

That said, you may want to try adjusting some of the smoothing parameters if the distribution and contents of the loci of interest are wildly different compared to CpGs in human & mouse. For example, if there are many more loci that are spaced closer together, to avoid over-smoothing you could try decreasing the maximum gap parameter (maximum number of base pairs allowed between two loci to be considered in the same DMR) and/or the base pair span and minimum number of loci in a smoothing span. On the contrary, if there are fewer loci that are spaced even further apart, you may boost power by allowing a larger maximum gap and/or increasing the smoothing level with the span parameters. 

Please don't hesitate to reach out if you have any further questions or suggestions.

Best,
Keegan
