### ISSUE TITLE
Error: failed to stop 'SOCKcluster' cluster: error writing to connection

### ISSUE THREAD

**Issue by ttriche** [kdkorthauer/dmrseq#10]
This is a new development; I'm not sure what's behind it.  But it's killing every dmrseq run now...

```
Retaining 561544 loci.
Assuming the test covariate tumor is a factor.
Condition: 1 vs 0
Parallelizing using 40 workers/cores (backend: BiocParallel:MulticoreParam).
                        
Detecting candidate regions with coefficient larger than 0.1 in magnitude.
...Chromosome chr22: Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
Error: failed to stop 'SOCKcluster' cluster: error writing to connection
```

Running the -3.4 branch from github as of 4/23/2018:

```
R> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /primary/projects/triche/lib64/R/lib/libRblas.so
LAPACK: /primary/projects/triche/lib64/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices datasets  utils
[8] methods   base

other attached packages:
 [1] biscuitEater_0.9.11        bsseq_1.14.0
 [3] SummarizedExperiment_1.8.1 DelayedArray_0.4.1
 [5] matrixStats_0.53.1         Biobase_2.38.0
 [7] GenomicRanges_1.30.3       GenomeInfoDb_1.14.0
 [9] IRanges_2.12.0             S4Vectors_0.16.0
[11] BiocGenerics_0.24.0        BiocInstaller_1.28.0
[13] skeletor_1.0.4             magrittr_1.5
[15] gtools_3.5.0               useful_1.2.3
[17] ggplot2_2.2.1              purrr_0.2.4
[19] knitr_1.20
   
loaded via a namespace (and not attached):
  [1] colorspace_1.3-2
  [2] XVector_0.18.0
  [3] roxygen2_6.0.1
  [4] bit64_0.9-7
  [5] interactiveDisplayBase_1.16.0
  [6] AnnotationDbi_1.40.0
  [7] qualV_0.3-3
  [8] xml2_1.2.0
  [9] codetools_0.2-15
 [10] R.methodsS3_1.7.1
 [11] impute_1.52.0
 [12] dmrseq_0.99.10
```

**Comment by kdkorthauer** [comment]
Hi @ttriche,

Thanks for the bug report. I think it is related to these recent issues in `bsseq`: hansenlab/bsseq#65 and `DelayedArray`: Bioconductor/DelayedArray#16

I'll follow up with the `bsseq`/`DelayedArray` authors about a fix.

Best,
Keegan

**Comment by kdkorthauer** [comment]
Hi @ttriche,

The issue has been fixed by the `bsseq` authors by swapping dependency on `MatrixStats` for `DelayedMatrixStats`. I can make this change for `dmrseq` if you are still getting the error after installing the newest version of `bsseq` from `hansenlab/bsseq`. Let me know; I have been unable to reproduce the error on my machines.

Best,
Keegan

**Comment by kdkorthauer** [comment]
Hi @ttriche,

I have updated the package to use the `rowSums2`, `rowMeans2`, `colSums2` and `colMeans2` functions from `DelayedMatrixStats`. I hope this resolves the issues you've been experiencing. These changes should propagate to the release version of Bioc 3.7 on May 1; in the meantime it's safer to install from Github during the transition.

Best,
Keegan

**Comment by ttriche** [comment]
Right on -- will do. Thanks for the fixes -- still playing with the various
options for dmrseq to tune it for [e]RRBS and mid-coverage WGBS -- but it's
a great framework.  My undergraduate intern who's planning to work on
N-of-1 permutations starts on May 14th, so it's great to resolve this now
rather than then :-)

Much obliged.

--t

**Comment by ttriche** [comment]
this is fixed by the rowMeans2/rowSums2 updates.  Thanks Keegan!
