### ISSUE TITLE
Is it a good idea to remove sites having less than 10 reads?

### ISSUE THREAD

**Issue by bishwaG** [kdkorthauer/dmrseq#13]
Hi,
When I have been using other RRBS/WGBS methods in the past, I have been filtering out methyalted/non-methyated Cytosines called from less than 10 reads. Is such coverage filtering approach recommended for dmrseq?

**Comment by kdkorthauer** [comment]
Hi @bishwaG,

That's a great question. For dmrseq, it is actually not required to remove low coverage sites, such as those with fewer than 10 reads. In our experience, this can remove many CpGs, especially if the overall coverage isn't very high. dmrseq is able to include CpGs with low coverage in DMR detection, and also down-weights the influence of low coverage CpGs relative to higher coverage CpGs.

Hope that helps!

Best,
Keegan

**Comment by bishwaG** [comment]
Thank you @kdkorthauer  for you prompt reply.

Regards,
BishwaG
