### ISSUE TITLE
Setting up a dmrseq analysis with paired data.

### ISSUE THREAD

**Issue by miilko** [kdkorthauer/dmrseq#15]
Hi,

I am trying to set up a dmrseq analysis with bisulfite sequencing data from several twin pairs discordant for memory function. I got a bit confused how the adjustCovariate and matchCovariate parameters in dmrseq() function work so how would you suggest including the pair info in the analysis?

**Comment by kdkorthauer** [comment]
Hi @miilko,

Thanks for the great question! It sounds like you would like to compare two groups, each of which contain one member of a twin pair but the groups differ by memory function phenotype. There is currently no option to carry out an explicit paired test using dmrseq, but you may treat the samples as independent for the purposes of identifying DMRs between phenotype groups. This may be conservative if there are large differences between twin pairs. 

If you'd like to proceed with treating the samples as independent, I would recommend setting the `matchCovariate` as the twin pair ID. This will prevent comparing complete sets of twins to one another (which would not be a null comparison). This will be less likely and less detrimental if you have more than two pairs of samples, but still advisable to prevent. 

I'm flagging this as an enhancement to look into adding an option for an explicit paired test, if possible, in the future.

Best,
Keegan

**Comment by miilko** [comment]
Thank you for the reply! I will try to proceed as you suggested. It would be great if a paired test can be added since there are not many tools like that for bisulfite sequencing data, at least to my knowledge. 

Best,
Mikko
