### ISSUE TITLE
Can dmrseq be used on single CpG sites?

### ISSUE THREAD

**Issue by Geetharv** [kdkorthauer/dmrseq#17]
Hi, 
I have RRBS data for specific genes (a few hundred genes). Firstly, I would like to perform differential methylation analysis on single CpG sites and then perform an analysis for DMRs. Can this package be used for single CpG sites? And what would be the recommended parameters to call dmrseq() when I have methylation data for a list of genes?
Thanks in advance.

Best wishes,
Geetha

**Comment by kdkorthauer** [comment]
Hi @Geetharv.

dmrseq is not designed to detect significantly differentially methylated single CpG sites. It is focused on analysis for DMRs. 

Regarding your second question, I suggest you check out the discussion regarding use of dmrseq with RRBS and choosing suitable parameters in this issue: #14. Please let me know if you still have questions.  

Best,
Keegan
