### ISSUE TITLE
Feature request: `compareTrack` more than 4

### ISSUE THREAD

**Issue by dktanwar** [kdkorthauer/dmrseq#18]
Hi @kdkorthauer!

Would it be possible for you to update the code to plot more than 4 `compareTrack`?
It would be nice to have this feature. Do you think, changing the dimensions of the plot could be taken care by `grid.arrange()`

**Comment by kdkorthauer** [comment]
Hi @dktanwar,

At this time, it is not possible to have more than 4 tracks plotted. If you are interested primarily in comparing annotation tracks, I suggest you to check out the [Gviz](http://bioconductor.org/packages/Gviz/) Bioconductor package. 

Best,
Keegan
