### ISSUE TITLE
Add support for unbalanced design

### ISSUE THREAD

**Issue by kdkorthauer** [kdkorthauer/dmrseq#2]
When two biological conditions have unequal number of samples, modify construction of null sample groups to allow for unequal number of samples in each condition.

**Comment by ttriche** [comment]
What is required to do this?  It would be incredibly handy for a set of contrasts I'm running, to the point that I'd be happy to implement it myself if I knew where to start.

**Comment by kdkorthauer** [comment]
Hi @ttriche,

The functionality for unbalanced comparisons has been added to dmrseq. You can obtain it immediately on the master branch and the R-3.4 branch (which exists to allow you to install without R-devel). This update will automatically propagate to the Bioconductor version next day or so.

As we discussed via Skype, I have added constraints that exclude permutation groups that contain only samples from one biological group (since this would not truly be null). Please try it out and let me know if you have any issues or suggestions!

Best,
Keegan
