### ISSUE TITLE
dmrseq fails while processing chromosomes/contigs

### ISSUE THREAD

**Issue by jckhearn** [kdkorthauer/dmrseq#24]
Hi @kdkorthauer,

I am running dmrseq on WGBS of a sparsely methylated genome and it is failing with the following error:

`Error in `[[<-.data.frame`(`*tmp*`, i, value = c(1L, 1L, 1L, 1L, 1L, 1L,  : 
  replacement has 480 rows, data has 240
Calls: dmrseq ... model.matrix -> model.matrix.default -> [[<- -> [[<-.data.frame`

The exact contig at which failure occurs varies according to the parameters applied to `dmrseq` but also crops up. I have filtered out contigs less than 1000bp.  

The experiment is a complex design with 48 replicates total and fails when testing 'Food' against 'Age' and 'Strain' as `adjustCovariates`:

`testFoodCovariate<-"Food"`
`matchStrainAgeCovariate<-c("Strain","Age")`
`Food <- dmrseq(bs= bismarkBSseq.filtered, cutoff = 0.05, testCovariate=testFoodCovariate,adjustCovariate=matchStrainAgeCovariate,maxPerms = 10)`

Food | Age | Strain
-- | -- | --
H | O | C32
H | O | C32
H | O | C32
H | O | C32
H | O | C32
H | O | C32
L | O | C32
L | O | C32
L | O | C32
L | O | C32
L | O | C32
L | O | C32
H | Y | C32
H | Y | C32
H | Y | C32
H | Y | C32
H | Y | C32
H | Y | C32
L | Y | C32
L | Y | C32
L | Y | C32
L | Y | C32
L | Y | C32
L | Y | C32
H | O | KA53
H | O | KA53
H | O | KA53
H | O | KA53
H | O | KA53
H | O | KA53
L | O | KA53
L | O | KA53
L | O | KA53
L | O | KA53
L | O | KA53
L | O | KA53
H | Y | KA53
H | Y | KA53
H | Y | KA53
H | Y | KA53
H | Y | KA53
H | Y | KA53
L | Y | KA53
L | Y | KA53
L | Y | KA53
L | Y | KA53
L | Y | KA53
L | Y | KA53

Bioconductor packages are up to date. Why do you think this error is occurring?

Thanks for any help!

**Comment by kdkorthauer** [comment]
Hi @jckhearn,

Would you mind sending me a small subset of your bsseq object (as an rds file) that throws the error so that I can see what's going on? Just a single chromosome or contig is sufficient, as long as it throws the error.

You can send to keegan@jimmy.harvard.edu if you'd prefer.

Thank you!
Best,
Keegan

**Comment by jckhearn** [comment]
Will do over the next couple of days!
Thanks,
Jack
