### ISSUE TITLE
MeDipSeq

### ISSUE THREAD

**Issue by dktanwar** [kdkorthauer/dmrseq#32]
Hi @kdkorthauer 

Is it possible to use dmrseq with MeDiP-Seq data?

If so, what would be the parameters to be considered?

**Comment by kdkorthauer** [comment]
Hi @dktanwar,

Thank you for the question. dmrseq was designed for bisulfite sequencing data, where we obtain basepair-level signal. Unfortunately, MeDIP sequencing provides peak-level signal, so it requires a different modeling approach. One idea could be to convert the MeDIP data into a rough basepair-level signal based on all reads aligning each site and then model with methods for bisulfite sequencing data, but this is not a direction I have explored. 

You may want to check out the [MEDIPS](http://www.bioconductor.org/packages/release/bioc/html/MEDIPS.html) Bioconductor package for working with your data.

Best,
Keegan
