### ISSUE TITLE
Dmrseq parameters for short regions

### ISSUE THREAD

**Issue by jckhearn** [kdkorthauer/dmrseq#33]
Hi,

I am running dmrseq on an organism with much shorter and sparser runs of CpG methylation (100s of bp) on average than vertebrates.

At the moment I am comparing default parameters with 'laxer' ones, detailed below:

`cutoff = 0.025`
`maxPerms = 25`
`minNumRegion = 3`
`bpSpan = 300`
`minInSpan = 5`

Is this a sound approach or can you suggest better parameter settings to explore for this analysis?

Thanks,
Jack

**Comment by kdkorthauer** [comment]
Hi Jack,

That sounds like a reasonable approach to detecting differential methylation where CpGs are sparser and the correlation is more local. The main parameters that will have an influence here are the 'bpSpan' and 'minInSpan'. I would suggest comparing a couple of different settings where these have been lowered (just as you proposed).

Best,
Keegan
