### ISSUE TITLE
ANOVA-like test for differences

### ISSUE THREAD

**Issue by biobenkj** [kdkorthauer/dmrseq#35]
Hi Keegan,

dmrseq is incredible. Thanks so much for writing it! It's been wildly useful for my work. I am now embarking on yet another deconvolution idea from WGBS or other bisulfite-flavored sequencing data. Many of the existing methods will have some sort of reference cell-type specific "signature" that you pass using significant features (whether that's DMP, DMR, VMP, VMR, etc.). I'd like to use something like the BLUEPRINT flow-sorted WGBS data (https://github.com/stephaniehicks/FlowSorted.Blood.WGBS.BLUEPRINT) and pull out a cell-specific set of DMRs using dmrseq using something akin to an ANOVA-like test for differences (I think?). Is there a way to do this in dmrseq already? Very open to whatever you think is most appropriate.

Thanks so much!

**Comment by kdkorthauer** [comment]
Hi Ben,

Thanks for your question; I'm glad to hear that dmrseq has been useful.

I want to make sure I understand your question before I try to answer. Are you looking to find regions that are differentially methylated among multiple groups (e.g. cell types), where the difference may be exhibited in one or more groups? If so, then yes, dmrseq is capable of carrying out this kind of test by including a multi-level factor covariate. Here, the null is that methylation among all groups is equal, and the DMRs identified are those that show evidence to the contrary.

If not, please clarify the type of test you are interested in (e.g. what would be the null hypothesis, and what kinds of differences would provide evidence against it), and hopefully I can provide some insight.

Best,
Keegan

**Comment by biobenkj** [comment]
Hi Keegan,

Thanks for the reply and my apologies for the very delayed response! Yes, the goal is to do what you allude to you with feeding dmrseq a multi-level factor covariate. Also, it turns out the methylCC paper that came out does exactly this on the dataset that I'm working with :) Please feel free to close this out.

Thanks again!

Ben
