### ISSUE TITLE
One suggestion regarding the prerequisite packages

### ISSUE THREAD

**Issue by xinkai-zhou** [kdkorthauer/dmrseq#4]
Hi Keegan, the paper introduced a very interesting idea and I'm curious to try it out. 

Just one simple suggestion regarding the prerequisite packages: since I'm new to WGBS methylation data, I don't have all the common annotation packages installed, and this prevents the **dmrseq** package from being properly installed. For example, I would get an error message like ```Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called 'TxDb.Rnorvegicus.UCSC.rn5.refGene'```.

I tried to install the required package and install **dmrseq** again, but then received a similar error message asking me to install another annotation package. 

Since this process seems rather inefficient, would it be possible to somehow give a list of prerequisite packages for the user to install before installing **dmrseq**?

Here are the annotation packages that I have installed manually so far:
```biocLite("TxDb.Hsapiens.UCSC.hg18.knownGene")
biocLite("TxDb.Dmelanogaster.UCSC.dm3.ensGene")
biocLite("TxDb.Dmelanogaster.UCSC.dm6.ensGene")
biocLite("TxDb.Hsapiens.UCSC.hg38.knownGene")
biocLite("TxDb.Mmusculus.UCSC.mm10.knownGene")
biocLite("TxDb.Mmusculus.UCSC.mm9.knownGene")
biocLite("TxDb.Rnorvegicus.UCSC.rn4.ensGene")
```

**Comment by xinkai-zhou** [comment]
seems related: https://github.com/hadley/devtools/issues/700

**Comment by kdkorthauer** [comment]
Hi @xinkai01,

Apologies for the late reply; it seems my email alerts were temporarily shut off.

I have revised the package to have fewer annotation dependencies, and these dependencies are all listed in the DESCRIPTION file. In addition, I have `biocViews:` in my DESCRIPTION file, so `install_github` should know to go and search Bioconductor for any missing dependencies. Please let me know if you continue to have trouble with installation and I'll troubleshoot further.

Best,
Keegan
