### ISSUE TITLE
Possibility to visualize results of different values bpSpan

### ISSUE THREAD

**Issue by tmms1** [kdkorthauer/dmrseq#41]
Dear @kdkorthauer 

Thank you for this very powerful and convenient tool. 

I am wondering if there is possibility to visualize what happens when the value of ``bpSpan`` is increased or decreased. Is it similar as what happens when the window size (span) of ``loess`` is modified? Smaller values capture "local trends", while larger values capture the "overall trend" like these plots illustrate: https://rafalab.github.io/dsbook/smoothing.html#local-weighted-regression-loess

I am trying to run ``dmrseq`` on data that is neither from human nor mouse. But I have no idea to assess if the modifications to ``bpSpan`` make sense. 

Thanks in advance.

--
With kind regards
Tim

**Comment by kdkorthauer** [comment]
Tim,

Sorry for the late reply and thanks for your question.

Yes, changing the value of bpSpan is analogous to changing the smoothing bandwidth. Your intuition is correct - smaller values capture local trends and larger values capture overall or lower resolution trends.

You can assess how changes in the bpSpan affect the resolution of your results by examining the distribution of the widths of DMRs. You should find that smaller values of bpSpan detect shorter regions, and larger values, which smooth over little bumps, may detect larger regions (if they exist). What I would recommend is to plot the top 10 or so regions for a few different spans. If you find that a region that appears to be differentially methylated according to the trend of the lines is broken up into short DMRs, then a larger bpSpan may be more appropriate. 

Hope that helps!

Best,
Keegan

**Comment by tmms1** [comment]
Thank you very much for the clear reply.
