### ISSUE TITLE
Targeted Methyl-Seq

### ISSUE THREAD

**Issue by hlkaatsch** [kdkorthauer/dmrseq#43]
Dear Keegan Korthauer,

we performed targeted methyl-seq experiments (TruSeq Methyl Capture EPIC Kit, Illumina) expecting overall low effects of the testcovariate. When looking for suitable analysis pipelines, we came across dmrseq and were wondering, if there are any reservations on your side regarding the evaluation of targeted methyl-seq data with dmrseq? I have already read the issue on RRBS and dmrseq - can we transfer the recommendations you made to our analysis?

Thank you very much in advance.

Best regards,

Leo

**Comment by kdkorthauer** [comment]
Hi Leo,

I would view targeted methyl-seq experiments as similar to RRBS in terms of analysis with dmrseq, so yes, I'd offer the same recommendations. Hope that helps!

Best,
Keegan

**Comment by hlkaatsch** [comment]
Thank you for the quick response!

Best regards,

Leo
