### ISSUE TITLE
block = TRUE with BiocParallel

### ISSUE THREAD

**Issue by stephen-siecinski** [kdkorthauer/dmrseq#44]
Thanks for putting together this great package!

I might be missing some obvious configuration step but it seems that dmrseq isn't utilizing multiple cores when performing block analysis. Is this expected behavior? Setting up BiocParallel as shown below works fine for the block = FALSE configuration. 

```
library("BiocParallel")
register(MulticoreParam(16))

dmrseq_object <- dmrseq(bs = bs_contrast,
                        cutoff = 0.1,
                        testCovariate = "treatment",
                        minNumRegion = 100,
                        smooth = TRUE,
                        bpSpan = 5000,
                        minInSpan = 200,
                        maxGapSmooth = 10000,
                        maxGap = 1000,
                        verbose = TRUE,
                        maxPerms = 20,
                        matchCovariate = NULL,
                        stat = "stat",
                        block = TRUE)
```

**Comment by kdkorthauer** [comment]
Hi Stephen,

Did you resolve this issue? Or are you still seeing that parallelization isn't working for block analysis?

**Comment by stephen-siecinski** [comment]
Hi Keegan,

Apologies for not updating this when I closed the post. Parallelization did indeed work with block analysis, I believe it was a quirk of the dataset where it appeared to hang on one processor for quite a while but later utilized more when processing (presumably) other DMRs / other chromosomes. 

Thanks again for putting together this great tool!
