### ISSUE TITLE
this tool could also be used in RRBS data or just WGBS?

### ISSUE THREAD

**Issue by sixone11** [kdkorthauer/dmrseq#45]
I have multi-groups  and want to find DMRs among them. 
Is it appropriate to use this tool?

Thanks in advance!

**Comment by kdkorthauer** [comment]
Hi,

Yes, you can use dmrseq for RRBS. For more discussion on this, see [this issue](https://github.com/kdkorthauer/dmrseq/issues/14).

**Comment by sixone11** [comment]
Thank you very much for your kind help!
