### ISSUE TITLE
Error in if (nrow(tab) == 0) { : argument is of length zero

### ISSUE THREAD

**Issue by xinkai-zhou** [kdkorthauer/dmrseq#5]
My guess is that the error comes from the bumphunt() function. 

```
Detecting candidate regions with coefficient larger than 0.05 in magnitude.
.....Computing coefficients.
.....Smoothing coefficients.
..........Done Smoothing Chromosome chr1. Took 0.03 minutes
.....Evaluating 13 candidate regions.
.....Took 3.06 min to score candidate regions.
Performing balanced permutations of condition across samples to generate a null distribution of region test statistics
Beginning permutation 1
.....Computing coefficients.
.....Smoothing coefficients.
..........Done Smoothing Chromosome chr1. Took 0 minutes
Error in if (nrow(tab) == 0) { : argument is of length zero
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
```

**Comment by KailiBio** [comment]
I have the same issue on running dmrseq, and I figured out that's because the chr size is too small to do the smooth. Try bigged data would work!

**Comment by kdkorthauer** [comment]
HI @xinkai01 and @KailiBio,

Thanks for reporting this issue. What happened in your example is that no null candidate regions were found in permutation 1. This may be OK if null candidates are found in other permutations. If not enough null candidates are detected, we have nothing to compare our observed regions with to perform inference. I have fixed the bug to allow subsequent permutations to be carried out, but if no null candidates are found in any permutations, an informative error message is printed. The error message suggests to (1) decrease the cutoff, or (2) include more data (relevant if you are currently looking at a subset). 

You can install the version with the bug fix with `devtools::install_github("kdkorthauer/dmrseq", ref="R-3.4")`. Please don't hesitate to reach out if you have any further questions or suggestions!

Best,
Keegan
