### ISSUE TITLE
Error in (function (cond)

### ISSUE THREAD

**Issue by dktanwar** [kdkorthauer/dmrseq#50]
Hi @kdkorthauer 

I am not sure what this error means. 

```
Assuming the test covariate group is a factor.
Condition: main2 vs main1
Adjusting for covariate (s): batch
Parallelizing using 10 workers/cores (backend: BiocParallel:MulticoreParam).
Computing on 1 chromosome(s) at a time.

Detecting candidate regions with coefficient larger than 0.1 in magnitude.
...Chromosome Chr1: Error in (function (cond)  : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': BiocParallel errors
  0 remote errors, element index: 
  1 unevaluated and other errors
  first remote error:
  ```
  
<details>

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS, RStudio 2022.7.1.554

Locale:
  LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
  LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
  LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

Package version:
  AnnotationDbi_1.58.0          AnnotationHub_3.4.0           annotatr_1.22.0               askpass_1.1                  
  assertthat_0.2.1              base64enc_0.1.3               bayestestR_0.13.0             beachmat_2.12.0              
  BH_1.78.0.0                   Biobase_2.56.0                BiocFileCache_2.4.0           BiocGenerics_0.42.0          
  BiocIO_1.6.0                  BiocManager_1.30.18           BiocParallel_1.30.3           BiocVersion_3.15.2           
  biomaRt_2.52.0                Biostrings_2.64.1             bit_4.0.4                     bit64_4.0.5                  
  bitops_1.0-7                  blob_1.2.3                    brew_1.0.7                    brio_1.1.3                   
  BSgenome_1.64.0               bslib_0.4.0                   bsseq_1.32.0                  bumphunter_1.38.0            
  cachem_1.0.6                  callr_3.7.2                   cli_3.3.0                     clipr_0.8.0                  
  codetools_0.2-18              colorspace_2.0-3              commonmark_1.8.0              compiler_4.2.1               
  cpp11_0.4.2                   crayon_1.5.1                  credentials_1.3.2             crosstalk_1.2.0              
  curl_4.3.2                    data.table_1.14.2             datawizard_0.6.2              DBI_1.1.3                    
  dbplyr_2.2.1                  DelayedArray_0.22.0           DelayedMatrixStats_1.18.1     desc_1.4.1                   
  details_0.3.0                 devtools_2.4.4                diffobj_0.3.5                 digest_0.6.29                
  dmrseq_1.16.0                 doRNG_1.8.2                   downlit_0.4.2                 dplyr_1.0.10                 
  DT_0.25                       effectsize_0.7.0.5            ellipsis_0.3.2                evaluate_0.16                
  fansi_1.0.3                   farver_2.1.1                  fastmap_1.1.0                 filelock_1.0.2               
  fontawesome_0.3.0             forcats_0.5.2                 foreach_1.5.2                 formatR_1.12                 
  fs_1.5.2                      futile.logger_1.4.3           futile.options_1.0.1          generics_0.1.3               
  GenomeInfoDb_1.32.4           GenomeInfoDbData_1.2.8        GenomicAlignments_1.32.1      GenomicFeatures_1.48.4       
  GenomicRanges_1.48.0          gert_1.8.0                    ggplot2_3.3.6                 gh_1.3.0                     
  gitcreds_0.1.1                glue_1.6.2                    graphics_4.2.1                grDevices_4.2.1              
  grid_4.2.1                    gtable_0.3.1                  gtools_3.9.3                  HDF5Array_1.24.2             
  highr_0.9                     hms_1.1.2                     htmltools_0.5.3               htmlwidgets_1.5.4            
  httpuv_1.6.5                  httr_1.4.4                    ini_0.3.1                     insight_0.18.4               
  interactiveDisplayBase_1.34.0 IRanges_2.30.1                isoband_0.2.5                 iterators_1.0.14             
  jquerylib_0.1.4               jsonlite_1.8.0                KEGGREST_1.36.3               knitr_1.40                   
  labeling_0.4.2                lambda.r_1.2.4                later_1.3.0                   lattice_0.20-45              
  lazyeval_0.2.2                lifecycle_1.0.1               limma_3.52.4                  locfit_1.5-9.6               
  magrittr_2.0.3                MASS_7.3.57                   Matrix_1.5-1                  MatrixGenerics_1.8.1         
  matrixStats_0.62.0            memoise_2.0.1                 methods_4.2.1                 mgcv_1.8.40                  
  mime_0.12                     miniUI_0.1.1.1                munsell_0.5.0                 nlme_3.1-157                 
  openssl_2.0.2                 outliers_0.15                 parallel_4.2.1                parameters_0.18.2            
  performance_0.10.0            permute_0.9-7                 pillar_1.8.1                  pkgbuild_1.3.1               
  pkgconfig_2.0.3               pkgdown_2.0.6                 pkgload_1.3.0                 plogr_0.2.0                  
  plyr_1.8.7                    png_0.1-7                     praise_1.0.0                  prettyunits_1.1.1            
  processx_3.7.0                profvis_0.3.7                 progress_1.2.2                promises_1.2.0.1             
  ps_1.7.1                      purrr_0.3.4                   R.cache_0.16.0                R.methodsS3_1.8.2            
  R.oo_1.25.0                   R.utils_2.12.0                R6_2.5.1                      ragg_1.2.2                   
  rappdirs_0.3.3                rcmdcheck_1.4.0               RColorBrewer_1.1-3            Rcpp_1.0.9                   
  RCurl_1.98-1.9                readr_2.1.2                   regioneR_1.28.0               rematch2_2.1.2               
  remotes_2.4.2                 report_0.5.5                  reshape2_1.4.4                restfulr_0.0.15              
  rhdf5_2.40.0                  rhdf5filters_1.8.0            Rhdf5lib_1.18.2               Rhtslib_1.28.0               
  rjson_0.2.21                  rlang_1.0.5                   rmarkdown_2.16                rngtools_1.5.2               
  roxygen2_7.2.1                rprojroot_2.0.3               Rsamtools_2.12.0              RSQLite_2.2.16               
  rstudioapi_0.14               rtracklayer_1.56.1            rversions_2.1.2               S4Vectors_0.34.0             
  sass_0.4.2                    scales_1.2.1                  sessioninfo_1.2.2             shiny_1.7.2                  
  snow_0.4.4                    sourcetools_0.1.7             sparseMatrixStats_1.8.0       splines_4.2.1                
  stats_4.2.1                   stats4_4.2.1                  stringi_1.7.8                 stringr_1.4.1                
  styler_1.7.0                  SummarizedExperiment_1.26.1   sys_3.4                       systemfonts_1.0.4            
  testthat_3.1.4                textshaping_0.3.6             tibble_3.1.8                  tidyselect_1.1.2             
  tinytex_0.41                  tools_4.2.1                   tzdb_0.3.0                    urlchecker_1.0.1             
  usethis_2.1.6                 utf8_1.2.2                    utils_4.2.1                   vctrs_0.4.1                  
  viridisLite_0.4.1             vroom_1.5.7                   waldo_0.4.0                   whisker_0.4                  
  withr_2.5.0                   writexl_1.4.0                 xfun_0.32                     XML_3.99-0.11                
  xml2_1.3.3                    xopen_1.0.0                   xtable_1.8-4                  XVector_0.36.0               
  yaml_2.3.5                    zip_2.2.0                     zlibbioc_1.42.0              

  </details>

**Comment by kdkorthauer** [comment]
Hi,

I'm not able to determine the cause of the error without knowing more about the inputs and how you're setting up the parallel environment. If you're willing to share a small de-identified subset of your data (for example, just one chromosome, or even smaller if it generates the same result), I'd be happy to try to diagnose. Let me know, and I'm happy to provide a dropbox link for upload if you need it.

Best,
Keegan

**Comment by dktanwar** [comment]
Hello, @kdkorthauer.

Thank you for your prompt response.

So, I discovered that there was a problem on my end. I misaligned my data as "non-directional" when it was actually "directional." I was able to successfully run 'dmrseq' after correctly aligning the data.

Thank you once more for this powerful tool.

**Comment by Xiangyi-Deng** [comment]
> Hello, @kdkorthauer.
> 
> Thank you for your prompt response.
> 
> So, I discovered that there was a problem on my end. I misaligned my data as "non-directional" when it was actually "directional." I was able to successfully run 'dmrseq' after correctly aligning the data.
> 
> Thank you once more for this powerful tool.

Hallo, could you tell me how do you solve this question ?

**Comment by kdkorthauer** [comment]
Hi,

Can you let me know what your question is? The text you quote from another user indicates that the cause of their error was before running dmrseq, due to incorrectly aligning the sequencing reads. They solved it by realigning with the correct settings to match what sequencing protocol they used.
