### ISSUE TITLE
Error in meanDiff function

### ISSUE THREAD

**Issue by delbala** [kdkorthauer/dmrseq#52]
Hi, 

I am running in to a problem when running the meanDiff function to get the methylation difference of DMRs.
All the previous steps worked, I got the DMRs but when I run the meanDiff function I get this error:
```
meanDiff(bs.filtered, dmrs=regions, testCovariate="condition")
Error in .Primitive("[")(c(1, 0.666666666666667, 1, 0.857142857142857,  : 
  subscript out of bounds
```
I checked my regions file and I don't have NA row.

Thanks for your help. 
Delphine

**Comment by kdkorthauer** [comment]
Hi @delbala,

Were you able to resolve this issue? If not, would you mind sending me a small example dataset where this occurs so I can reproduce the error?

Thanks!
