### ISSUE TITLE
About plot feature: addPoints or not

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#53]
Hi @kdkorthauer 

It is a wonderful package I have ever met during DNA methylation visualization.

The gene infomation and its structure in figures produced by dmrseq satisfied what I want.

I have a small question concerning points in plot.

I tried to remove points by using parameter addPoints=F,  however, it means the lines will show as "un-BSmoothed" ?

So it means I cannot remove points but I can remove lines ?

I initially know bsseq package, and it can show only BSmoothed lines without points if I like.

So, do you know how to do like that?

If I overlook some parameters that can do this ?

Thank you.

**Comment by kdkorthauer** [comment]
Hi @DengEr-1993,

Thank you for pointing out this inconsistent behaviour of the plotting function. I will look into this and see if it is possible to make the expected result (the smoothed lines without points will be shown when only `addPoints = FALSE`). 

Best,
Keegan (she/her/hers)

**Comment by kdkorthauer** [comment]
I've tracked down the issue and pushed changes that should have the plotting function working as expected. The changes should be reflected in both the devel (3.17) and current release (3.16) versions of Bioconductor within a day or two. Please reinstall the updated version (if you are using the release version, dmrseq will be version 1.18.1) and let me know if you have any more questions.
