### ISSUE TITLE
How to produce dmrseq figure by defining specific gene symbol ?

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#54]
Sorry  @kdkorthauer

It is my second question.  

For example,  I want to show specific gene symbol and its CpG methylation points or regions.

So how can I  specify this gene by annoTrack, regions&blocks or even the bsseq result  ?

Or should I do this procedure manually ?
##############

Thanks!

**Comment by kdkorthauer** [comment]
Hi @DengEr-1993,

You can add gene tracks to the plot using the `annoTrack` argument in `plotDMRs` (you pass the output of `getAnnot`) - see [this section](https://www.bioconductor.org/packages/release/bioc/vignettes/dmrseq/inst/doc/dmrseq.html#53_Plot_DMRs) of the vignette for example. Note that if there are no genes in the region plotted, then no gene tracks will be shown. 

Best,
Keegan (she/her/hers)

**Comment by Xiangyi-Deng** [comment]
@kdkorthauer  Thank you for you answer. You may not understand my question. I know how to add the gene information through the `annoTrack` parameter and it works perfect.

But I want to show one gene that I am interested in. For example,  the gene SAMD11 (I select it randomly here), if it has significance after `dmrseq`, and then I want to see methylation on this gene. So how should I do to focus this region ?Thank you.

**Comment by kdkorthauer** [comment]
The purpose of the function is really focused on visualizing DMRs. To do what you are proposing, you would need to construct that region yourself (e.g. a region containing SAMD11) and pass it to the plotting function. Or, select the DMR(s) that overlap a region containing your gene of interest using `GenomicRanges` functions, and then pass that to the plotting function. Hope that helps!

Best,
Keegan
