### ISSUE TITLE
Could multiple groups compared be plotted in figure ?

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#55]
Hello @kdkorthauer

I have a small question about  the function` makeBSseqData` in dmrseq:

I want to show multiple groups which can be compared with each other.

So if I can input them labeled with different groups in ` makeBSseqData` ?

For example: 

```
BSobj <- makeBSseqData(list(A1, A2,              ##  group 1
                            B1,B2,B3,  ## group 2
                            C1,C2,    ##  group 3
                            D1,D2,     ## group 4
                            E1,E2      ##  group 5 
                              ## and more groups ...
                            ),
                       c(paste0("A",1:2),
                         paste0("B",1:3), 
                         paste0("C",1:2), 
                         paste0("D",1:2), 
                         paste0("E",1:2)))

###  Then follow the next steps 

##  especially here:
testCovariate stands for five groups
regions <- dmrseq(bs=bs.filtered,
                  cutoff = 0.05,
                  testCovariate=testCovariate)

```

And get the plot in the end ?

Can I do it  ?

**Comment by Xiangyi-Deng** [comment]
Sorry, I tried it and it worked. But it showed the same sample lines.  So I think if  samples in in the same group can be merged as only one line ? Is it possible  ?

**Comment by kdkorthauer** [comment]
Hi @DengEr-1993,

There is no function in dmrseq called `makeBSseqData`. This is a function in a different package, so if your question is related to this function, please refer to that package's documentation and maintainers.

It seems like you are also asking a question about plotting, but I'm not sure what your question is. Please clarify if this is true. 

Best,
Keegan

**Comment by Xiangyi-Deng** [comment]
@kdkorthauer I am sorry about that. I made a mistake.
