### ISSUE TITLE
Volcano plot from dmrseq

### ISSUE THREAD

**Issue by katkat-ri** [kdkorthauer/dmrseq#59]
Hello,

And sorry if this is very obvious because some issues over 'stat' and 'beta' do exist, though I am not sure I understand in what context to use them

1. I have run dmrseq and I was wondering which is the best value to use in a volcano plot, in my x axis, clearly indicating the methylation difference. I have seen people use beta coefficient or delta beta..or even stat, but without clarity. What metric is in your opinion the best for a Volcano plot? 

Two additional questions because I do not have a great grasp of the statistics part of the package:

2. How can I find the delta-beta value from my regions object? I only get one beta column and I have one test covariate, with 2 groups. Is there a way to get a beta value for Group A one for Group B, and then substract them? 

3. Which is the metric that shows the methylation difference in a proportion (0-100%) ? 

Thank you in advance I hope my questions are not very confusing :)

Katri

**Comment by kdkorthauer** [comment]
Hi Katri,

Happy to share my thoughts on these questions.

1. The volcano plot should typically have a measure of effect size (e.g. beta coefficient or delta beta) on the x-axis, and a measure of significance (e.g. -log10(pvalue) or the test statistics) on the y-axis. 

2. To obtain the raw mean methylation difference (i.e. delta beta) you can use the `meanDiff` function in dmrseq

3. See previous question, but with the caveat that this value is the 'raw' mean methylation difference, meaning it will not reflect any adjustments for covariates, if any were included in the model - see issue #28 for related discussion 

Hope that helps!
