### ISSUE TITLE
How to combinde several samples with different dimensions ?

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#60]
Hello there,

I have several RRBS CpG results samples (CpG.txt format)which have different dimensions. 

In order to do some analysis based on dmrseq,  I have to convert them into Bsseq format files and then combine them together.

There are many methods to combine them together, for example:

1. combine()  from bsseq 
2. read.bismark() from dmrseq 
3. makeBSseqDat() from DSS

But all of them need methylation matrix with the same dimensions. 

Actually, samples from the same or different groups have their own numbers of CpGs.

So I believe there must be better method to combine sample together.

Could you give me some advice on this step ? Or what I thought is wrong ?

Thank you very much.

**Comment by kdkorthauer** [comment]
Hi @DengEr-1993,

As none of these functions are from dmrseq (`read.bismark()` is actually a bsseq function), I'd suggest you refer to the documentation from those packages, and reach out to the respective maintainers if you're still stuck. Thanks!

**Comment by Xiangyi-Deng** [comment]
@kdkorthauer  Sorry for that I made mistakes.  Thanks anyway.
