### ISSUE TITLE
Something wrong with the running of dmrseq()

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#61]
Hello there,

I use dmrseq() with below parameters:

> blocks <- dmrseq(bs=bs.filtered,
>                  cutoff = 0.1,
>                  minNumRegion = 3, ##  default 5
>                  smooth = T,
>                  testCovariate = "CellType",
>                  block = TRUE,
>                  #BPPARAM = BiocParallel::bpparam(),
>                  #BPPARAM = MulticoreParam(workers=6,progressbar=TRUE),
>                  BPPARAM=bpparam(),##  wrong
>                  
>                  minInSpan = 30,
>                  bpSpan = 1000,
>                  
>                  maxGapSmooth = 1e6,
>                  maxGap = 5e4)

But no matter which BPPARAM = I used, the error information always appeared: 

Searching for large scale blocks with at least 5000 basepairs.
Performing a global test of H0: no difference among 6 groups (assuming the test covariate CellType is a factor).
Parallelizing using 6 workers/cores (backend: BiocParallel:MulticoreParam).
Computing on 1 chromosome(s) at a time.

Detecting candidate regions with coefficient larger than 0.1 in magnitude.
  |=============================================================================================================================| 100%

  |===========                                                                                                                  |   9%
Error in (function (cond)  : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': BiocParallel errors
  1 remote errors, element index: 118
  1225 unevaluated and other errors
  first remote error:
Error in qr.default(t(const)): NA/NaN/Inf in foreign function call (arg 1)
In addition: There were 16 warnings (use warnings() to see them)

##

By the way,  the below script works well but it takes a long time. 

> 
> regions <- dmrseq(bs=bs.filtered,
>                   cutoff = 0.1,
>                   smooth = T,
>                   testCovariate = "CellType",
>                   minInSpan = 500,
>                   bpSpan = 5e4,
>                   maxGapSmooth = 1e6,
>                   maxGap = 5e3)

When I set block = TRUE,  the step doesn't work. 

I tried to add  one of below three parameters but the error still exists.
>                  #BPPARAM = BiocParallel::bpparam(),
>                  #BPPARAM = MulticoreParam(workers=6,progressbar=TRUE),
>                  #BPPARAM=bpparam(),##  wrong

So could you give me some advice on this problem ?  Thanks a lot.

**Comment by kdkorthauer** [comment]
Hi,

Thanks for reporting your issue. Could you try to find a small subset of your data that reproduces the same error? If you could send this subset to me as an .rds file [here](https://www.dropbox.com/request/VcTNJmpxKyuK1WtnpLX5), then I can better diagnose the root cause. 

Thank you!
Keegan

**Comment by Xiangyi-Deng** [comment]
> Hi,
> 
> Thanks for reporting your issue. Could you try to find a small subset of your data that reproduces the same error? If you could send this subset to me as an .rds file [here](https://www.dropbox.com/request/VcTNJmpxKyuK1WtnpLX5), then I can better diagnose the root cause.
> 
> Thank you! Keegan

Thanks for your response. I will double check that. If I cannot solve this question, I will send subset to you.

**Comment by Xiangyi-Deng** [comment]
> Hi,
> 
> Thanks for reporting your issue. Could you try to find a small subset of your data that reproduces the same error? If you could send this subset to me as an .rds file [here](https://www.dropbox.com/request/VcTNJmpxKyuK1WtnpLX5), then I can better diagnose the root cause.
> 
> Thank you! Keegan

Hello, it is solved automatically. Maybe it is caused by my computer. Thanks.
