### ISSUE TITLE
Can dmrseq be used on several groups but single sample in each group ?

### ISSUE THREAD

**Issue by Xiangyi-Deng** [kdkorthauer/dmrseq#63]
Hello there,
 
I have a question about dmrseq() function in this package.

There are 5 groups and more than 2 replicates in each group.  I have idea that if dmrseq() can compare single sample between groups?

Because I want to use the average value of replicates in each group to visualize similar result between groups.

I tried to do this but it doesn't work through dmrseq(). Maybe it needs replicates to do differential analysis.  

Another questions is if I can compare these expression level of single sample between groups, I should calculate the average values of Coverage and methylation, respectively. It is a little complicated. 

But it doesn't matter.  Could you just give me some advice on my first question ?

Thank you very much.

Best,
xiangyi

**Comment by kdkorthauer** [comment]
Hi Xiangyi,

dmrseq requires replicates in each group to perform statistical inference. Comparisons of single samples is not possible with this methodology. 

Best,
Keegan
