### ISSUE TITLE
Do no need "testCovariate" 

### ISSUE THREAD

**Issue by zhen-fu** [kdkorthauer/dmrseq#67]
Hi Keegan,

Thanks for the great package! I do have a quick question if I do not need to testCovariate, is there anyway I can still run dmrseq function without setting "testCovariate"? 

Thank you very much!

**Comment by kdkorthauer** [comment]
Hi @zhen-fu, Can you clarify the goal of your analysis, if there are no differences of interest? Thanks!

**Comment by zhen-fu** [comment]
I am so sorry, I think I totally misunderstood testCovariate in the vignette. 

For some reason I thought testCovariate is the the covariate that we want to adjusting for. I guess here it means it is the main factor that we are interested, like the celltype (imr90 and h1) in your BS.chr21. So sorry about this!
